# Utilities

cask "rectangle"

cask "postman"

brew "gum"

brew "ag"

brew "gnupg"

brew "gnupg2"

brew "tmux"

brew "wget"

# Terminals
cask "iterm2"

# Browsers
cask "google-chrome"

# Communication
cask "slack"
cask "skype"

# Video player
cask "vlc"

# Docker For Mac
cask "docker"

# Ruby tools
brew "readline"

brew "openssl@1.1"

# tree
brew "tree"

# jq
brew "jq"

# nmap
brew "nmap"

# nmap
brew "thefuck"

# gh
brew "gh"

# direnv
brew "direnv"


# coreutils
brew "coreutils"

# yq
brew "yq"

# Git
brew "git"

# Git Duet
tap "git-duet/tap"
brew "git-duet"

# Ripgrep
brew "ripgrep"

# asdf
brew "asdf"

# Neovim
brew "neovim"


cask "1password"

cask "1password-cli"

brew "watch"

brew "rsync"

cask "spotify"

cask "microsoft-teams"

cask "nordvpn"

cask "caffeine"

cask "git-credential-manager"

cask "cool-retro-term"

# Browsers
cask "obsidian"
