# Utilities

cask "spectacle"
cask "postman"

brew "gum"
brew "ag"
# brew "gpg"
brew "tmux"
brew "wget"

# Terminals
cask "iterm2"

# Browsers
cask "google-chrome"

# Communication
cask "slack"
cask "skype"


# Docker For Mac
cask "docker"

# Ruby tools
brew "readline"

brew "openssl@1.1"

# tree
brew "tree"

# jq
brew "jq"

# nmap
brew "nmap"

# hub
brew "hub"

# direnv
brew "direnv"


# coreutils
brew "coreutils"

# yq
brew "yq"

# Git and associated tools
brew "git"

tap "git-duet/tap"
brew "git-duet"
# asdf
brew "asdf"

# Neovim
brew "neovim"


cask "1password"

brew "watch"
brew "rsync"


cask "nordvpn"

cask "caffeine"

cask "git-credential-manager"

# Browsers
cask "obsidian"
